behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.175
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 3
      vis_encode_type: resnet
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 2000
    summary_freq: 5000
    self_play:
      save_steps: 30000
      team_change: 100000
      swap_steps: 5000
      window: 10
      play_against_latest_model_ratio: 0.3
      initial_elo: 1200.0

